# Generated by Django 5.1 on 2024-10-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
    ]
