# Generated by Django 5.1 on 2024-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_alter_patients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Cedula',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Policy_state',
            field=models.BooleanField(default=False, verbose_name='Valid Policy?'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='policy_number',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Insurance Number'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='policy_validity',
            field=models.DateField(default='0001-01-01', verbose_name='Insurance Active Until'),
        ),
    ]
