# Generated by Django 5.1 on 2024-10-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0003_medicalrecords_datecreated'),
        ('medicineInventory', '0002_medicineinventory_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRMedicineI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('idMedicalRecords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.medicalrecords')),
                ('idMedicineInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicineInventory.medicineinventory')),
            ],
            options={
                'verbose_name': 'MedicalRMedicineI',
                'verbose_name_plural': 'MedicalRMedicineI',
            },
        ),
    ]
