# Generated by Django 5.1 on 2024-10-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='created',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='idMedicineInventory',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='modified',
        ),
    ]
