# Generated by Django 5.1 on 2024-10-21 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0002_remove_medicalrecords_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecords',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
