# Generated by Django 5.1 on 2024-10-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0003_medicalrecords_datecreated'),
        ('TypeAppointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecords',
            name='idTypeAppointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TypeAppointment.typeappointment'),
            preserve_default=False,
        ),
    ]
