# Generated by Django 5.1 on 2024-10-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='idPatient',
            new_name='idPatients',
        ),
        migrations.AlterField(
            model_name='billing',
            name='paymentStatus',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEND', 'Pendiente')], default='PEND', max_length=20, verbose_name='Estado de pago'),
        ),
    ]
