# Generated by Django 5.1 on 2024-10-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAppointment', models.CharField(max_length=100, verbose_name='Nombre cita')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'TypeAppointment',
                'verbose_name_plural': 'TypeAppointment',
            },
        ),
    ]
