# Generated by Django 5.1 on 2024-10-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
